[BUGFIX] - useAssistant - Check for empty array
vercel/ai pull request #1184
Opened 2024-03-19 16:25 UTC by tchanxx

When I was using the `useAssistant` hook, I noticed this error: `Unhandled Runtime Error
TypeError: Cannot set properties of undefined (setting 'id')`

![image](https://github.com/vercel/ai/assets/46210938/ccf7269f-c4f8-497e-aea9-3e31eff267fa)

This error was kind of cryptic since it doesn't say which element in `useAssistant` is causing this error. However, I figured out that it's due to `lastMessage` being undefined in the following code:
```
const lastMessage = messages[messages.length - 1];
  return [
    ...messages.slice(0, messages.length - 1),
    {
      id: lastMessage.id,
      role: lastMessage.role,
      content: lastMessage.content + value,
    },
  ];
  ```
  
  When `messages` has a length of `0`, then `lastMessage` becomes undefined and then we get a runtime error at `lastMessage.id`.

2024-03-20 07:33 UTC, lgrammel commented
There should always be a message at the point when text fragments start streaming in, so the root cause could be different. Can you share the code that caused this bug? One potential cause could be using `setMessages` while there is ongoing streaming.

2024-03-20 07:34 UTC, lgrammel requested changes
Marking as on hold for now. The fix most likely needs to be more involved.

2024-03-20 14:13 UTC, tchanxx commented
> One potential cause could be using `setMessages` while there is ongoing streaming.

@lgrammel Ahh that's a good point. It's hard for me to share the entire code, but basically I have a setup similar to below:

```tsx
useEffect(() => {
  if (selectedThread) {
    fetchMessages()
  } else {
    setChatMessages([])
  }
}, [selectedThread, setChatMessages])


const handleSendMessage = async () => {
  let currentThread = selectedThread ? { ...selectedThread } : null

  if (!currentThread) {
    currentThread = await handleCreateThread(
      user.id,
      userInput,
      chatSettings!,
      selectedWorkspace!,
      setSelectedThread,
      setThreads
    )
  }

  await submitMessage()
}
```

I think my issue is that when I create a new thread in `handleSendMessage()`, I create a new thread and then call `setSelectedThread()` which triggers the `useEffect()` hook to clear my messages via `setChatMessages([])` but those are all asynchronous calls so `setChatMessages([])` may happen during `await submitMessage()`. 

I can reconfigure my app so that it relies on the thread creation in the `useAssistant()` hook instead of creating it separately which should resolve this issue.

-----------

I am curious though, in this `useAssistant()` code, how does it ensure that there's always a message in the array before hitting those `lastMessage` code? [This part is async so it can't be guaranteed](https://github.com/vercel/ai/blob/8ca4096b5dd4f90d9ffafef43e9a2e0c10d3a468/packages/core/react/use-assistant.ts#L139C5-L142C8) to complete first so that means `assistant_message` or `data_message` would always have to be sent before `text` or `assistant_control_data`? 

I am looking at the streaming code and it seems that `assistant_control_data` [is always enqueued first](https://github.com/vercel/ai/blob/fac9a6ee7c3aca975f7dd9f2f40cda1b82a1f8f3/packages/core/streams/assistant-response.ts#L88-L96) so that may cause the `id` issue I'm seeing as well?

2024-03-20 14:21 UTC, lgrammel commented
> I am curious though, in this `useAssistant()` code, how does it ensure that there's always a message in the array before hitting those `lastMessage` code? [This part is async so it can't be guaranteed](https://github.com/vercel/ai/blob/8ca4096b5dd4f90d9ffafef43e9a2e0c10d3a468/packages/core/react/use-assistant.ts#L139C5-L142C8) to complete first so that means `assistant_message` or `data_message` would always have to be sent before `text` or `assistant_control_data`?
> 
> I am looking at the streaming code and it seems that `assistant_control_data` [is always enqueued first](https://github.com/vercel/ai/blob/fac9a6ee7c3aca975f7dd9f2f40cda1b82a1f8f3/packages/core/streams/assistant-response.ts#L88-L96) so that may cause the `id` issue I'm seeing as well?

The OpenAI stream sends a `thread.message.created` event first, before the text delta stream starts. This trigger the sending of an `assistant_message`: https://github.com/vercel/ai/blob/fac9a6ee7c3aca975f7dd9f2f40cda1b82a1f8f3/packages/core/streams/assistant-response.ts#L50

2024-03-20 17:21 UTC, lgrammel commented
> @lgrammel Sorry, I'm still confused. Isn't `assistant_control_data` enqueued prior to `forwardStream` being called here?
> 
> https://github.com/vercel/ai/blob/fac9a6ee7c3aca975f7dd9f2f40cda1b82a1f8f3/packages/core/streams/assistant-response.ts#L88-L105

Yes, first there is a control data message, then the `assistant_message`, and then the streaming. Am I missing something?

2024-03-20 18:11 UTC, tchanxx commented
If the data control message comes first, then couldn't this fail since `messages` may be empty then `lastMessage` is undefined? 

https://github.com/vercel/ai/blob/main/packages/core/react/use-assistant.ts#L212-L223

2024-03-27 08:17 UTC, lgrammel commented
> If the data control message comes first, then couldn't this fail since `messages` may be empty then `lastMessage` is undefined?
> 
> https://github.com/vercel/ai/blob/main/packages/core/react/use-assistant.ts#L212-L223

Yes, good point. This would need a check if there are any messages.

2024-03-27 08:19 UTC, lgrammel commented
@tchanxx  Can you update the PR to only check in the control data part, and move the if check outside of setMessages?

2024-03-27 08:19 UTC, lgrammel commented on packages/core/react/use-assistant.ts
> +              }
This can be checked before setMessages, e.g. like this:

```
if (messages.length > 0) {
  setMessages ...
}

2025-06-27 06:10 UTC, closed without merging