Update nextjs app router guide to use ai/rsc
vercel/ai pull request #1189
Opened 2024-03-19 23:29 UTC by jeremyphilemon

2024-03-19 23:46 UTC, jaredpalmer commented on docs/pages/docs/guides/frameworks/nextjs-app.mdx
> +import { generate } from './actions';
should we call this generate? given `generateText` coming?

2024-03-19 23:48 UTC, jaredpalmer commented on docs/pages/docs/guides/frameworks/nextjs-app.mdx
> +import { generate } from './actions';
should we call this generate? given `generateText` coming?

2024-03-19 23:48 UTC, jaredpalmer commented on docs/pages/docs/guides/frameworks/nextjs-app.mdx
> +  render({
why not have `const ui = render()` and then return `ui` from the stream?

2024-03-19 23:50 UTC, jaredpalmer requested changes

2024-03-19 23:50 UTC, jaredpalmer commented on docs/pages/docs/guides/frameworks/nextjs-app.mdx
> +  return {
Missing other APIs and or links to them.

2024-03-19 23:50 UTC, jaredpalmer commented on docs/pages/docs/guides/frameworks/nextjs-app.mdx
>  Note that using the Edge Runtime is optional but highly recommended due to [longer streaming timeouts on Vercel](https://vercel.com/docs/concepts/functions/edge-functions/limitations#maximum-initial-
Remove this

2024-04-04 23:43 UTC, kevingyang approved these changes

2024-06-05 09:30 UTC, lgrammel commented
@jeremyphilemon can this be closed?

2024-06-05 09:32 UTC, closed without merging