Refactor(streams): improve type safety and readability
vercel/ai pull request #139
Opened 2023-06-17 18:22 UTC by sirlolcat

### Changes:
- **Added JSDoc Comments**: Added JSDoc comments to interfaces and functions. This would help in understanding the purpose of interfaces and functions at a glance.
- **Variable Renaming for Clarity**: Renamed variables to be more descriptive.
  - Renamed `decoder` to `textDecoder`.
  - Renamed `parser` to `eventSourceParser`.
  - Renamed `fullResponse` to `aggregatedResponse`.
  - Renamed `res` to `response`.
- **Type Narrowing for Safety**: Implemented type narrowing to handle TypeScript errors related to property access on union types (e.g., `ParsedEvent | ReconnectInterval`). This ensures that we are accessing properties in a type-safe manner.
- **Created a Utility Function**: Extracted the logic for creating an empty `ReadableStream` into a separate utility function called `createEmptyReadableStream`. This adheres to the DRY (Don't Repeat Yourself) principle.
- **Code Formatting**: Applied consistent formatting to the entire file. This includes consistent use of semicolons and whitespace.

### Benefits:
- **Readability**: The JSDoc comments and more descriptive variable names make the code easier to read and understand.
- **Maintainability**: Extracting logic into utility functions and improving naming conventions makes the code easier to maintain and modify in the future.
- **Type Safety**: The implemented type narrowing technique prevents runtime errors and ensures that the code is robust.

Please let me know if there are any changes or adjustments you would like.

2023-06-17 18:25 UTC, sirlolcat commented
I noticed that during the last PR, the prettier action failed as well; I would like to have more information on how I can stay consistent on prettier setup with the team. Thanks.

2023-06-18 11:43 UTC, sirlolcat commented
I would also like to purpose the benefit of applying this refactor to the code-base as it grows to ensure it's maintainability. I would be happy to take that into action. Let me know about it.

2023-06-18 13:42 UTC, jaredpalmer requested changes
This is great! Can you add JSDoc comments to all exports? (but please leave further refactoring for another PR)

2023-06-18 13:43 UTC, jaredpalmer commented on packages/core/streams/ai-stream.ts
> + * Interface representing callbacks for an AIStream.
```suggestion
 * Helper callback methods for stream lifecycle events
```

2023-06-18 13:55 UTC, jaredpalmer requested changes

2023-06-18 13:55 UTC, jaredpalmer commented on packages/core/streams/ai-stream.ts
> + * Interface representing a custom parser for AIStream data.
In comments, lets just say what is immediately and remove the `Interface representing...` parts

2023-06-18 13:55 UTC, jaredpalmer commented on packages/core/streams/ai-stream.ts
> - * This stream forks input stream, allowing us to use the result as a
This is a more informative comment. Lets not lose important contributor information that could be helpful for newcomers.

2023-06-18 13:55 UTC, jaredpalmer commented on packages/core/streams/ai-stream.ts
> +export function trimStartOfStreamHelper(): (text: string) => string {
This removes valuable comment information. Let's not lose valuable information.

2023-06-18 13:55 UTC, jaredpalmer commented on packages/core/streams/ai-stream.ts
> + * Creates an AIStream from the response.
Comment needs more detail. Comments should not include the name of the method they are describing in the first sentence. Should be phrased like `Returns a ...`

2023-06-18 13:56 UTC, jaredpalmer commented
On second thought, lets actually break this into different PRs. First lets fix type-safety and then move JSDoc comments to another PR

2023-06-18 14:25 UTC, sirlolcat commented
@jaredpalmer if you are on the same page with the changes for type-safety, I can create a branch out of this one and move all the JSDocs there; let me know if that works out for you.

2023-06-18 16:22 UTC, jaredpalmer commented
Need to run prettier

2023-06-18 16:22 UTC, jaredpalmer commented
TS seems fine

2023-06-18 16:46 UTC, sirlolcat commented
> Need to run prettier

All fine now.

2023-06-20 19:32 UTC, CarlosZiegler commented
Great PR :)

2023-06-20 19:42 UTC, MaxLeiter approved these changes

2023-06-20 19:42 UTC, merged

2023-06-20 19:43 UTC, MaxLeiter commented
Thank you!