Update: fix typos in 03-openai-assistants.mdx
vercel/ai pull request #1556
Opened 2024-05-10 18:11 UTC by DraganAleksic99

2024-05-10 18:13 UTC, DraganAleksic99 commented
I think that first part of the Configure Request Options section is not correct. By default, useAssistant hook does not send a request to /api/completion endpoint, the api property of useAssistantOptions is a required property :)

2024-05-10 18:34 UTC, MISTYKITTY reviewed
****

2024-05-10 18:47 UTC, lgrammel requested changes
Thanks! found one small mistake

2024-05-10 18:47 UTC, lgrammel commented on content/docs/05-ai-sdk-ui/03-openai-assistants.mdx
> +In this example, the `useAssistant` hook sends a POST request to the `/api/custom-completion` endpoint with the specified headers, additional body fields, and credentials for that fetch request. On y
It's `/api/assistant` (line 19)

2024-05-10 19:54 UTC, DraganAleksic99 commented on content/docs/05-ai-sdk-ui/03-openai-assistants.mdx
> +In this example, the `useAssistant` hook sends a POST request to the `/api/custom-completion` endpoint with the specified headers, additional body fields, and credentials for that fetch request. On y
Done!

2024-05-11 06:53 UTC, lgrammel approved these changes

2024-05-11 06:53 UTC, merged

2024-05-11 06:53 UTC, lgrammel commented
Great thank you!

2024-05-11 11:35 UTC, DraganAleksic99 commented
You're welcome!