feat: add solid helpers and solidstart example
vercel/ai pull request #340
Opened 2023-07-17 00:01 UTC by ryoid

Adapted from vue helpers.

2023-07-18 18:16 UTC, MaxLeiter commented
hey @ryoid, thanks so much for the PR, we'd love to support Solid.

After some thought, would you mind moving the example to it's own repo? We're starting to add some bloat and affecting DX with the additional packages. I'd be happy to link to your repo from the docs

2023-07-18 18:19 UTC, MaxLeiter requested changes
thanks a lot @ryoid! Would you mind adding a changeset with `pnpm changeset` and addressing my small comments?

2023-07-21 12:59 UTC, ryoid commented on examples/solidstart-openai/postcss.config.cjs
> +module.exports = {
Yep, the example is from solidstart's `with-tailwind` template

2023-07-21 13:09 UTC, ryoid commented on examples/solidstart-openai/.gitignore
> +
done

2023-07-21 20:11 UTC, MaxLeiter requested changes

2023-07-21 20:11 UTC, MaxLeiter commented on .changeset/friendly-owls-think.md
> +'ai': minor
this should be a `patch`

2023-07-21 21:02 UTC, MaxLeiter approved these changes

2023-07-21 21:02 UTC, merged