Add `onError` handler to useAssistant hook
vercel/ai pull request #818
Opened 2023-12-02 06:45 UTC by mfts

similar to `useChat` exposing an `onError` handler on the useAssistant hook. 

```tsx
const { status, messages, input, submitMessage, handleInputChange, error } =
    useAssistant({
      api: '/api/assistant',
      onError: err => { 
        console.error(err.message);
      },
    });
```

2023-12-04 15:53 UTC, lgrammel reviewed
Thanks, this looks great!

2023-12-06 07:03 UTC, mfts commented on packages/core/react/use-assistant.ts
> +  const [error, setError] = useState<unknown | Error>(undefined);
Thanks for picking that up.

2023-12-06 16:39 UTC, lgrammel approved these changes

2023-12-06 19:02 UTC, lgrammel commented
Build failure seems to be related to changes in PR.

2023-12-27 08:15 UTC, mfts commented
> Build failure seems to be related to changes in PR.

Sorry for the slow response. I created a proper `Error` and passed it in. That should fix the issue.

2023-12-28 03:00 UTC, mfts commented
fixed the prettier format error

2023-12-30 23:21 UTC, MaxLeiter requested changes
Thanks @mfts! Can you update the `OptionTable` in `docs/pages/docs/api-reference/use-assistant.mdx`?

2024-01-31 08:44 UTC, mfts commented
Added documentation

2024-01-31 16:46 UTC, MaxLeiter approved these changes

2024-01-31 17:43 UTC, merged