Expose setInput for useAssistant hook
vercel/ai pull request #886
Opened 2023-12-26 21:20 UTC by mathu97

This exposes the setInput callback in the `useAssistant` hook, similar to the `useChat` hook. 

This would be helpful to use Assistants with [Vercel's NextJS Chatbot Template](https://github.com/vercel/ai-chatbot).

2023-12-26 22:49 UTC, mathu97 commented
@lgrammel i'd appreciate it if you could take a look whenever you can!

2023-12-27 01:02 UTC, MaxLeiter requested changes
Thanks! Can you update the `OptionTable` in `/docs/pages/docs/api-reference/use-assistant.mdx` to match?

2023-12-27 05:40 UTC, mathu97 commented
> Thanks! Can you update the `OptionTable` in `/docs/pages/docs/api-reference/use-assistant.mdx` to match?

done!

2023-12-30 23:11 UTC, MaxLeiter approved these changes
Thanks!

2023-12-30 23:19 UTC, merged